# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubekit < Formula
  desc "Terminal UI for Kubernetes and AWS workflows."
  homepage "https://github.com/Tyka95/kube-kit"
  version "0.1.15"
  license "MIT"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.15/kubekit_0.1.15_macos_x86_64.tar.gz"
      sha256 "40f142faef15f45623700d150c38a854972ce395c4a298b53b23a42968a30b1f"

      define_method(:install) do
        bin.install "kubekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.15/kubekit_0.1.15_macos_arm64.tar.gz"
      sha256 "c3ddd24d23c346fa96220b0f42e9330bad6a39be18604ab4b73da19f05decf57"

      define_method(:install) do
        bin.install "kubekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.15/kubekit_0.1.15_linux_x86_64.tar.gz"
      sha256 "2e1c6faa093687b5f06d7d3127ea5e76499fe0277b2e8ae2b7dbb5f94c5c1823"
      define_method(:install) do
        bin.install "kubekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.15/kubekit_0.1.15_linux_arm64.tar.gz"
      sha256 "c8792d4c6f4fe703868074f6ec4150ad9a22de85757eef276cce8e679e30e1f2"
      define_method(:install) do
        bin.install "kubekit"
      end
    end
  end

  test do
    system "#{bin}/kubekit", "--version"
  end
end
