# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubekit < Formula
  desc "Terminal UI for Kubernetes and AWS workflows."
  homepage "https://github.com/Tyka95/kube-kit"
  version "0.1.19"
  license "MIT"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.19/kubekit_0.1.19_macos_x86_64.tar.gz"
      sha256 "ec8436dedbf9a2de32bbd3fe67a896bcb4d621514862f84e4ab8c8c2d2d8e429"

      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.19/kubekit_0.1.19_macos_arm64.tar.gz"
      sha256 "00260a82ff450af8665769883212d7f7156ad5f589c069a7df362ce76b328db7"

      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.19/kubekit_0.1.19_linux_x86_64.tar.gz"
      sha256 "529214e69c25e4ff2847d29a5dee559badeb540870d6232e4396f5be12cc6904"
      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.19/kubekit_0.1.19_linux_arm64.tar.gz"
      sha256 "7c5beac0482054fe319a63d4d66be55eedaca68cc111f481216a453224bd4a4d"
      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
  end

  test do
    system "#{bin}/kubekit", "--version"
    system "#{bin}/kube", "--version"
  end
end
