# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubekit < Formula
  desc "Terminal UI for Kubernetes and AWS workflows."
  homepage "https://github.com/Tyka95/kube-kit"
  version "0.1.16"
  license "MIT"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.16/kubekit_0.1.16_macos_x86_64.tar.gz"
      sha256 "7eb1803653d7d122029255dfc7084e2b745fb716c2a4ba1c1256bea00baf50bb"

      define_method(:install) do
        bin.install "kubekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.16/kubekit_0.1.16_macos_arm64.tar.gz"
      sha256 "279082fe222da79613ac65b3fd8d30c360e8c1a89876b018180361d6b0fe8f0f"

      define_method(:install) do
        bin.install "kubekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.16/kubekit_0.1.16_linux_x86_64.tar.gz"
      sha256 "d7d9d60d4dbac800ed9b826fd32ff52c2428992ca51377408be47841c50a365a"
      define_method(:install) do
        bin.install "kubekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.16/kubekit_0.1.16_linux_arm64.tar.gz"
      sha256 "48d4b415a007843fab28fb7d4903724facfe1e0e5d12692681d2c4f2422961e4"
      define_method(:install) do
        bin.install "kubekit"
      end
    end
  end

  test do
    system "#{bin}/kubekit", "--version"
  end
end
