# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubekit < Formula
  desc "Terminal UI for Kubernetes and AWS workflows."
  homepage "https://github.com/Tyka95/kube-kit"
  version "0.1.17"
  license "MIT"

  depends_on "awscli"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.17/kubekit_0.1.17_macos_x86_64.tar.gz"
      sha256 "18354a079bafe9f5db7257a73ed5b5800078f85a2dc64062d1f5dd85385249bc"

      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.17/kubekit_0.1.17_macos_arm64.tar.gz"
      sha256 "6f4117a06cccce468532937cb72c081dc06a0f010cfada04352adadc4b940570"

      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.17/kubekit_0.1.17_linux_x86_64.tar.gz"
      sha256 "ef66d4c3f059e9995aa8e8b351ab9a408e56a038c652a6554465544d2415ca85"
      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tyka95/kube-kit/releases/download/v0.1.17/kubekit_0.1.17_linux_arm64.tar.gz"
      sha256 "afb57f2b3424ffcb104f5279fe683a383a4c1ced9f772b9283d27fbda13302fe"
      define_method(:install) do
        bin.install "kubekit"
        # Keep the short `kube` alias for backward compatibility with the
        # bash version, which exposed both names.
        bin.install_symlink "kubekit" => "kube"
      end
    end
  end

  test do
    system "#{bin}/kubekit", "--version"
    system "#{bin}/kube", "--version"
  end
end
